### ISSUE TITLE
Stale dependency on guzzlehttp/guzzle 

### ISSUE THREAD

**Issue by rgcarr** [renanbr/crossref-client#18]
The latest release of Drupal (10) has a dependency on  `guzzlehttp/guzzle` at ^7.5 (whereas `crossref-client` dependency on guzzle is at ^7.4), so wondering if there was any activity on reviewing the dependencies and updating as required.

**Comment by rgcarr** [comment]
Would it be just as simple as changing `"guzzlehttp/guzzle": "^6.2 || ^7.4",` to `"guzzlehttp/guzzle": "^6.2 || ^7.5",` in composer.json?
[crossref-client-guzzle-version.patch](https://github.com/renanbr/crossref-client/files/13250132/crossref-client-guzzle-version.patch)

I've no idea about how to test this library if it's using a different version of guzzle.

**Comment by renanbr** [comment]
@rgcarr, as described in [Composer's documentation](https://getcomposer.org/doc/articles/versions.md#caret-version-range-), `^6.2 || ^7.4` allows installing `7.5`. The current constraint doesn't seem be the blocker.

May you share the output of `composer why guzzlehttp/guzzle`?

**Comment by rgcarr** [comment]
Thank you for your comment @renanbr (and thank you for your work on this library)
```
> composer why guzzlehttp/guzzle

drupal/core              10.1.6 requires guzzlehttp/guzzle (^7.5)
drush/drush              12.4.2 requires guzzlehttp/guzzle (^7.0)
php-http/guzzle7-adapter 1.0.0  requires guzzlehttp/guzzle (^7.0)
```

However, I think there may be a circular dependency somewhere else (cache/array-adapter, psr/cache or rtheunissen/guzzle-rate-limiter). So I'm closing this issue, as it seems the cause lies elsewhere
